Import('env')
client_env  = env
client_env.Append(LIBPATH=['$objroot/client'])
client_env.Prepend(LIBS=['client'])

client_env.StaticLibrary(
  target = 'client',
  source = [
   'client_connection.hpp',
   'client_connection.cpp',
   ],
   )

Test(env, 'rpc')
Test(env, 'listen')
#client_env.Program(
#  target = 'rpc_main',
#  source = ['rpc_main.cpp'])
