Import('env')
client_env  = env.Copy()
client_env.Append(LIBPATH=['$objroot/client', '$objroot/proto',
'$objroot/server'])
client_env.Prepend(LIBS=['client', 'hello_pb', 'server', 'meta_pb'])

client_env.StaticLibrary(
  target = 'client',
  source = [
   'client_connection.hpp',
   'client_connection.cpp',
   ],
   )

Test(client_env, 'rpc')
Test(client_env, 'listen')
client_env.Program(
  target = 'rpc_main',
  source = ['rpc_main.cpp'])
