Import('env')
server_env  = env.Copy()
server_env.Append(LIBPATH=['$objroot/server', '$objroot/proto',
'$objroot/client'])
server_env.Prepend(LIBS=['server', 'meta_pb', 'hello_pb'])
ProtoLib(server_env, 'meta')

server_env.StaticLibrary(
  target = 'server',
  source = [
   'connection.hpp',
   'connection.cpp',
   'io_service_pool.cpp',
   'io_service_pool.hpp',
   'protobuf_connection.cpp',
   'protobuf_connection.hpp',
   'server.cpp',
   'server.hpp',
   'client_connection.hpp',
   'client_connection.cpp',
   'raw_connection.hpp',
   'raw_connection.cpp',
   'raw_protobuf_connection.hpp',
   'raw_protobuf_connection.cpp',
   'timer_master.hpp',
   'timer_master.cpp',
   '$objroot/server/libmeta_pb.a'],
   )
server_env.Program(
  target = 'server0',
  source = ['posix_main.cpp'])

server_env.Program(
  target = 'client0',
  source = ['posix_client.cpp'])

Test(server_env, 'io_service_pool')
Test(server_env, 'shared_const_buffers')
Test(server_env, 'rpc')
Test(server_env, 'listen')
Test(server_env, 'timer_master')
server_env.Program(
  target = 'rpc_main',
  source = ['rpc_main.cpp'])
