Import('env')
server_env  = env.Copy()
server_env.Append(LIBPATH=['$objroot/server', '$objroot/proto',
'$objroot/client'])
server_env.Prepend(LIBS=['server', 'meta_pb', 'hello_pb', 'client'])
ProtoLib(server_env, 'meta')

server_env.StaticLibrary(
  target = 'server',
  source = ['connection.hpp',
   'io_service_pool.cpp',
   'io_service_pool.hpp',
   'protobuf_connection.cpp',
   'protobuf_connection.hpp',
   'server.cpp',
   'server.hpp'],
   )
server_env.Program(
  target = 'server0',
  source = ['posix_main.cpp'])

server_env.Program(
  target = 'client0',
  source = ['posix_client.cpp'])

Test(server_env, 'io_service_pool')
Test(server_env, 'shared_const_buffers')
