Import('env')
server_env  = env
server_env.Append(LIBPATH=['$objroot/server'])
server_env.Append(LIBS=['server'])

server_env.StaticLibrary(
  target = 'server',
  source = ['connection.hpp',
   'io_service_pool.cpp',
   'io_service_pool.hpp',
   'protobuf_connection.cpp',
   'protobuf_connection.hpp',
   'server.cpp',
   'server.hpp'],
   )

server_env.Program(
  target = 'server0',
  source = ['posix_main.cpp'])
